### ISSUE TITLE
Indeks ke database sqlite

### ISSUE THREAD

**Issue by abrari** [lafzi/lafzi-indexer#7]
Membuat database sqlite yang bisa dipakai di lafzi/lafzi-android. Ikut struktur tabel yang sudah dibuat @harunalfat. Database isinya bukan cuma indeks tapi juga seluruh data lain (ayat, terjemah, mapping posisi).

**Comment by harunalfat** [comment]
Strukturnya bisa diubah lagi aja kak @abrari supaya lebih optimal

Highlight posisi bisa disimpan di table ayat quran saja. Untuk index, mungkin bisa simpan json encoded? Sekarang juga lookup pakai term udah tarik semua ayat sih.

**Comment by abrari** [comment]
Iya sih. Kalau yang sekarang kan satu term di banyak record. Mungkin itu bikin database sqlite-nya gede. Kalau dibikin satu term satu record dan postlist-nya json encoded mungkin bisa lebih kecil ukurannya.

Dengan asumsi gak nambah overhead buat decode json.

**Comment by harunalfat** [comment]
Decodenya kayaknya costnya ga gede. Bisa gitu aja sih, lebih cepat juga kayaknya lookupnya karena rownya jadi sedikit, dan ga perlu index lagi karena primary key bisa langsung termnya. Harusnya sih lebih kecil size sqlitenya :+1:

**Comment by abrari** [comment]
Btw dari `android.provider.BaseColumns` bukannya harus kolom `_id` sebagai primary key?

**Comment by harunalfat** [comment]
Ga harus sih, interfacenya ga wajib diikutin. Bisa kita define dengan nama lain kok. Tapi untuk convention (gaya Android), pakai nama `_id` cuma typenya text

**Comment by abrari** [comment]
Merged #8 

File database ada di folder index/lafzi.sqlite

**Comment by harunalfat** [comment]
:+1:
